### ISSUE TITLE
Any further thoughts?

### ISSUE THREAD

**Issue by rob-luke** [GuillaumeFavelier/pyvista_github_actions#1]
Hi @GuillaumeFavelier,

Did you have any luck solving this issue in the end? Or do you have a hunch as to what the issue might be? Or how I might investigate this further? Or do you think that it won't be possible to generate 3D brain figures in MNE on GitHub actions? In which case I will have to migrate to circle ci?

I am happy to dig in to any areas that you suggest I investigate.

Thanks again for your time creating this repo,
Rob

**Comment by GuillaumeFavelier** [comment]
> Did you have any luck solving this issue in the end?

AFAIK, I did not manage to get it to work for all testing examples and now that some time has passed, I do not remember the details sorry :pray: 

> Or do you think that it won't be possible to generate 3D brain figures in MNE on GitHub actions?

I can't give a definite answer at the moment because I did not manage to pinpoint the origin of the issue but CircleCI is the safe plan in this situation for sure.

I actually have the time to give it a try again this week and this time I'll share my thoughts in here :+1:

**Comment by rob-luke** [comment]
> I actually have the time to give it a try again this week and this time I'll share my thoughts in here

Awesome, thanks for thinking about this again. I will hold off on moving to CircleCi for a bit longer then. Please let me know if there is anything I can help with.

**Comment by GuillaumeFavelier** [comment]
I use a basic setup of sphinx-gallery for testing. I also test different levels of integration of MNE-python with minimal examples:

* `plot_pyvista` uses only PyVista

* `plot_pyvistaqt` uses PyVista and PyVistaQt

* `plot_mne_renderer` uses PyVista, PyVistaQt, `_Figure` and `_Renderer`

* `plot_mne` is a fully integrated mne-python example (`plot_alignment`)

I was able to confirm that using:

```
pyvista.OFF_SCREEN = True
pyvista.BUILDING_GALLERY = True
```

is enough to make `plot_pyvista` and `plot_pyvistaqt` work on GitHub Actions, even with line smoothing, ~anti aliasing~, depth peeling and smooth shading.

But something goes wrong with `plot_mne_renderer`. I created [a branch of mne](https://github.com/GuillaumeFavelier/mne-python/tree/proto/sphinx_gha) to investigate further and I can confirm that the issue is related to `_Renderer`. I need to do more test to understand which parameter exactly causes this.

I hope that fixing `plot_mne_renderer` will also fix `plot_mne`.

---

**EDIT**: I narrowed it down to `enable_aa` and it totally makes sense if we consider that we had the same issue on Azure. Maybe because both services are operated by the same company, they could share the same runners?

I will proceed by using full examples of MNE and when I confirm that everything is okay, I will open a PR.

You could also try out the https://github.com/GuillaumeFavelier/mne-python/tree/proto/sphinx_gha branch and verify that everything works on your side @rob-luke?

This is what I added in `.github/workflows/ci.yml` : 

```
pip install --progress-bar off https://github.com/GuillaumeFavelier/mne-python/zipball/proto/sphinx_gha
```

---

**EDIT**: it's also possible to support STCs but sphinx needs to be configured accordingly (`_BrainScraper`, `_Resetter` and `pyvista.OFF_SCREEN=False`), similarly to https://github.com/mne-tools/mne-python/blob/main/doc/conf.py

These are the results of the [artifacts](https://github.com/GuillaumeFavelier/pyvista_github_actions/suites/4507604606/artifacts/120380107) on 4be7baec05dee90cd941f9affb24ffd86ca7fdf8

![image](https://user-images.githubusercontent.com/18143289/144073362-a0337f7a-5aa4-445f-be28-de2346507c49.png)

**Comment by rob-luke** [comment]
Thanks for all your help @GuillaumeFavelier !!!
